config/routes.rb
Wdbd::Application.routes.draw do

  resources :users

  resources :categories

  resources :books do
    resources :copies do
      member do
        post 'new_rent'
        post 'renew_rent'
        post 'finish_rent'
        post 'new_reservation'
        post 'execute_reservation'
        post 'cancel_reservation'
      end
    end
    member do
      get 'categories', :as => 'categories_of'
      post 'add_category', :as => 'add_category_of'
    end
  end
  match '/book/:id/remove_category/:category_id' => 'books#remove_category', :via => :delete, :as => 'remove_category_of_book'

  resources :authors

  root :to => 'books#index'

end

app/models/copy.rb
class Copy < ActiveRecord::Base
  attr_accessible :book_id, :edition_number, :publish_year

  belongs_to :book
  has_many :rentals
  has_many :reservations

  validates_presence_of :book
  validates_associated :book

  def current_rental
  	day = Date.today
  	rentals.where('begin_date <= ? and end_date >= ?', day, day)
  end
end

app/controllers/copies_controller.rb
class CopiesController < ApplicationController
  # GET /copies.json
  # GET /copies
  def index
    @book = Book.find(params[:book_id])
    @copies = @book.copies

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @copies }
    end
  end

  # GET /copies/1
  # GET /copies/1.json
  def show
    @book = Book.find(params[:book_id])
    @copy = @book.copies.find(params[:id])
    @users = User.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @copy }
    end
  end

  # GET /copies/new
  # GET /copies/new.json
  def new
    @book = Book.find(params[:book_id])
    @copy = @book.copies.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @copy }
    end
  end

  # GET /copies/1/edit
  def edit
    @book = Book.find(params[:book_id])
    @copy = @book.copies.find(params[:id])
  end

  # POST /copies
  # POST /copies.json
  def create
    @book = Book.find(params[:book_id])
    @copy = @book.copies.build(params[:copy])

    respond_to do |format|
      if @copy.save
        format.html { redirect_to book_copies_path(@book), notice: 'Copy was successfully created.' }
        format.json { render json: @book, status: :created, location: @copy }
      else
        format.html { render action: "new" }
        format.json { render json: @copy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /copies/1
  # PUT /copies/1.json
  def update
    @book = Book.find(params[:book_id])
    @copy = @book.copies.find(params[:id])

    respond_to do |format|
      if @copy.update_attributes(params[:copy])
        format.html { redirect_to book_copies_path(@book), notice: 'Copy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @copy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /copies/1
  # DELETE /copies/1.json
  def destroy
    @book = Book.find(params[:book_id])
    @copy = @book.copies.find(params[:id])
    @copy.destroy

    respond_to do |format|
      format.html { redirect_to book_copies_path(@book) }
      format.json { head :no_content }
    end
  end

  def new_rent
    @book = Book.find(params[:book_id])
    @copy = @book.copies.find(params[:id])
    rental = @copy.rentals.build(user_id: params[:user_id], begin_date: Date.today)
    rental.save

    redirect_to [@book, @copy]
  end

  def new_reservation
    @book = Book.find(params[:book_id])
    @copy = @book.copies.find(params[:id])
    reservation = @copy.reservations.build(user_id: params[:user_id], reservation_date: Date.today)
    reservation.save

    redirect_to [@book, @copy]
  end

  def execute_reservation
    @book = Book.find(params[:book_id])
    @copy = @book.copies.find(params[:id])
    reservation = @copy.reservations.find(params[:reservation_id])
    rental = @copy.rentals.build(user_id: reservation.user_id, begin_date: Date.today)
    if rental.save
      reservation.destroy
    end

    redirect_to [@book, @copy]
  end

  def cancel_reservation
    @book = Book.find(params[:book_id])
    @copy = @book.copies.find(params[:id])
    reservation = @copy.reservations.find(params[:reservation_id])
    reservation.destroy

    redirect_to [@book, @copy]
  end

  def renew_rent
    @book = Book.find(params[:book_id])
    @copy = @book.copies.find(params[:id])
    rental = @copy.rentals.find(params[:rental_id])
    rental.last_renewal = Date.today
    rental.save

    redirect_to [@book, @copy]
  end

  def finish_rent
    @book = Book.find(params[:book_id])
    @copy = @book.copies.find(params[:id])
    rental = @copy.rentals.find(params[:rental_id])
    rental.end_date = Date.today
    rental.save

    redirect_to [@book, @copy]
  end
end

app/helpers/copies_helper.rb
module CopiesHelper

  def current_state(copy)
  	rental = copy.current_rental.first
  	if rental
  		link_to "#{I18n.t(:rent_until)} #{rental.end_date}", [copy.book, copy]
  	elsif copy.reservations.count > 0
  		link_to "#{current_reservations.cout} #{I18n.t(:reservations)}", [copy.book, copy]
  	else
  		link_to I18n.t(:available), [copy.book, copy]
  	end
  end
end

app/views/copies/_form.html.erb
<%= form_for([@book, @copy]) do |f| %>
  <% if @copy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@copy.errors.count, "error") %> prohibited this copy from being saved:</h2>

      <ul>
      <% @copy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :book_id %>

  <div class="field">
    <%= f.label :edition_number %><br />
    <%= f.text_field :edition_number %>
  </div>
  <div class="field">
    <%= f.label :publish_year %><br />
    <%= f.number_field :publish_year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/copies/edit.html.erb
<h1><%=t 'Editing copy' -%></h1>

<%= render 'form' %>

<%= link_to t('Back'), @book %>

app/views/copies/index.html.erb
<h1><%=t :listing_copies_of -%> <%= link_to @book.title, @book -%></i></h1>

<table>
  <tr>
    <th>Id</th>
    <th><%=t 'Edition number' -%></th>
    <th><%=t 'Publish year' -%></th>
    <th><%=t :current_state -%></th>
    <th colspan="2"></th>
  </tr>

<% @copies.each do |copy| %>
  <tr>
    <td><%= copy.id %></td>
    <td><%= copy.edition_number %></td>
    <td><%= copy.publish_year %></td>
    <td><%= current_state(copy) %></td>
    <td><%= link_to t('Edit'), edit_book_copy_path(@book, copy) %></td>
    <td><%= link_to t('Destroy'), [@book, copy], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('New Copy'), new_book_copy_path(@book) %> | 
<%= link_to t(:back), @book %>

app/views/copies/new.html.erb
<h1><%=t 'New copy' -%> <%= link_to @book.title, @book -%></h1>

<%= render 'form' %>

<%= link_to t('Back'), @book %>

app/views/copies/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%=t 'Copy of' -%> <%= link_to @book.title, @book -%></h1>
<p>
  <b>Edition number:</b>
  <%= @copy.edition_number %><br />
  <b>Publish year:</b>
  <%= @copy.publish_year %>
</p>

<div id="rentals">
<h2><%=t :rentals -%></h2>

<ul>
	<% @copy.rentals.each do |rental| %>
	<li>
		<%= rental.user.full_name -%>
		<%=t :since -%>
		<% if rental.last_renewal %>
		<%= rental.last_renewal -%> (<%= rental.begin_date -%>)
		<% else %>
		<%= rental.begin_date -%>
		<% end %>
		<% if rental.end_date %>
			<%=t :until -%>
			<%= rental.end_date -%>
		<% else %>
			<%= link_to t(:renew_rent), renew_rent_book_copy_path(@book, @copy, :rental_id => rental), :method => :post %> |
			<%= link_to t(:finish_rent), finish_rent_book_copy_path(@book, @copy, :rental_id => rental), :method => :post %>
		<% end %>
	</li>
	<% end %>
</ul>
</div>

<div id="reservations">
<h2><%=t :reservations -%></h2>

<ul>
	<% @copy.reservations.each do |reservation| %>
	<li>
		<%= reservation.user.full_name -%>
		<%= reservation.reservation_date -%>
		<%= link_to t(:execute_reservation), execute_reservation_book_copy_path(@book, @copy, :reservation_id => reservation), :method => :post %> |
		<%= link_to t(:cancel_reservation),   cancel_reservation_book_copy_path(@book, @copy, :reservation_id => reservation), :method => :post %>
	</li>
	<% end %>
</ul>
</div>

<div id="actions">
<p>
	<%= form_tag new_rent_book_copy_path(@book, @copy) do -%>
	<h3><%=t :new_rental -%></h3>
	<div class="field">
		<%= label_tag :user_id, t('User') -%><br />
		<%= select_tag :user_id, options_from_collection_for_select(@users, :id, :full_name) %>
	</div>
	<div class="actions">
		<%= submit_tag t(:make_a_rent) %>
	</div>
	<% end %>
</p>

<p>
	<%= form_tag new_reservation_book_copy_path(@book, @copy) do -%>
	<h3><%=t :new_reservation -%></h3>
	<div class="field">
		<%= label_tag :user_id, t('User') -%><br />
		<%= select_tag :user_id, options_from_collection_for_select(@users, :id, :full_name) %>
	</div>
	<div class="actions">
		<%= submit_tag t(:make_a_reservation) %>
	</div>
	<% end %>
</p>

</div>

<%= link_to t('Edit'), edit_book_copy_path(@book, @copy) %> |
<%= link_to t('Back'), @book %>