config/routes.rb
Wdbd::Application.routes.draw do

  resources :users

  resources :categories

  resources :books do
    resources :copies do
      member do
        post 'new_rent'
        post 'renew_rent'
        post 'finish_rent'
        post 'new_reservation'
        post 'execute_reservation'
        post 'cancel_reservation'
      end
    end
    member do
      get 'categories', :as => 'categories_of'
      post 'add_category', :as => 'add_category_of'
    end
  end
  match '/book/:id/remove_category/:category_id' => 'books#remove_category', :via => :delete, :as => 'remove_category_of_book'

  resources :authors

  root :to => 'books#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :birth_year, :death_year, :forename, :surname

  has_many :books

  scope :by_year, order(:birth_year)
  default_scope order(:surname, :forename)

  def full_name
    "#{forename} #{surname}"
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
      format.xml { render xml: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
      format.xml { render xml: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :forename %><br />
    <%= f.text_field :forename %>
  </div>
  <div class="field">
    <%= f.label :surname %><br />
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :birth_year %><br />
    <%= f.text_field :birth_year %>
  </div>
  <div class="field">
    <%= f.label :death_year %><br />
    <%= f.text_field :death_year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1><%=t 'Editing author' -%></h1>

<%= render 'form' %>

<%= link_to t('Show'), @author %> |
<%= link_to t('Back'), authors_path %>

app/views/authors/index.html.erb
<h1><%=t 'Listing authors' -%></h1>

<table>
  <tr>
    <th><%=t 'Author name' -%></th>
    <th><%=t 'Birth year' -%></th>
    <th><%=t 'Death year' -%></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= link_to author.full_name, author %></td>
    <td><%= author.birth_year %></td>
    <td><%= author.death_year %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('New Author'), new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%=t :author -%>: <%= @author.full_name -%></h1>

<p>
  <b><%=t 'Forename' -%>:</b>
  <%= @author.forename %>
</p>

<p>
  <b><%=t 'Surname' -%>:</b>
  <%= @author.surname %>
</p>

<p>
  <b><%=t 'Birth year' -%>:</b>
  <%= @author.birth_year %>
</p>

<p>
  <b><%=t 'Death year' -%>:</b>
  <%= @author.death_year %>
</p>

<h2><%=t :books -%></h2>
<ul>
	<% @author.books.each do |book| -%>
	<li><%= link_to book.title, book -%></li>
	<% end %>
</ul>

<p>
<%= link_to t('New Book'), new_book_path(:author_id => @author) %>
</p>


<%= link_to t('Edit'), edit_author_path(@author) %> |
<%= link_to t('Destroy'), @author, method: :delete, data: { confirm: t('Are you sure?') } %> |
<%= link_to t('Back'), authors_path %>