config/routes.rb
Wdbd::Application.routes.draw do

  resources :users

  resources :categories

  resources :books do
    resources :copies do
      member do
        post 'new_rent'
        post 'renew_rent'
        post 'finish_rent'
        post 'new_reservation'
        post 'execute_reservation'
        post 'cancel_reservation'
      end
    end
    member do
      get 'categories', :as => 'categories_of'
      post 'add_category', :as => 'add_category_of'
    end
  end
  match '/book/:id/remove_category/:category_id' => 'books#remove_category', :via => :delete, :as => 'remove_category_of_book'

  resources :authors

  root :to => 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author_id, :description, :publish_year, :rental_length, :title

  belongs_to :author
  has_many :book_categories
  has_many :categories, :through => :book_categories
  has_many :copies

  default_scope order(:title)

  validates_presence_of :title
  validates_associated :author
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
      format.xml { render xml: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new
    @book.author_id = params[:author_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  def categories
    @book = Book.find(params[:id])
  end

  def add_category
    @book = Book.find(params[:id])
    @category = @book.book_categories.build(category_id: params[:category_id])
    @category.save
    redirect_to categories_of_book_path(@book)
  end

  def remove_category
    @book = Book.find(params[:id])
    @book.book_categories.where(category_id: params[:category_id]).each do |category|
      category.destroy
    end
    redirect_to categories_of_book_path(@book)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author_id %><br />
    <%= f.collection_select :author_id, Author.all, :id, :full_name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :publish_year %><br />
    <%= f.number_field :publish_year %>
  </div>
  <div class="field">
    <%= f.label :rental_length %><br />
    <%= f.number_field :rental_length %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/categories.html.erb
<h1><%=t :listing_categories_of -%> <%= link_to @book.title, @book -%></i></h1>

<table>
  <tr>
    <th><%=t :category -%></th>
    <th></th>
  </tr>

<% @book.categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to t('Destroy'), remove_category_of_book_path(@book, category.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<h3><%=t :new_category -%></h3>
<%= form_tag(add_category_of_book_path(@book)) do %>
  <p>
    <%=t :category -%>:
    <%= select_tag :category_id, options_from_collection_for_select(Category.all, :id, :name) %>
  </p>
  <p><%= submit_tag -%></p>
<% end %>

<%= link_to t(:back), @book %>

app/views/books/edit.html.erb
<h1><%=t 'Editing book' -%></h1>

<%= render 'form' %>

<%= link_to t('Show'), @book %> |
<%= link_to t('Back'), books_path %>

app/views/books/index.html.erb
<h1><%=t 'Listing books' -%></h1>

<table>
  <tr>
    <th><%=t 'Author' -%></th>
    <th><%=t 'Title' -%></th>
    <th><%=t 'Description' -%></th>
    <th><%=t 'Publish year' -%></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= link_to book.author.full_name, book.author %></td>
    <td><%= link_to book.title, book %></td>
    <td><%= truncate(book.description, :length => 100) %></td>
    <td><%= book.publish_year %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('New Book'), new_book_path %>

app/views/books/new.html.erb
<h1><%=t 'New book' -%></h1>

<%= render 'form' %>

<%= link_to t('Back'), books_path %>

app/views/books/show.html.erb
<h1><%=t :book -%>: <%= @book.title -%></h1>

<p id="notice"><%= notice %></p>

<p>
  <b><%=t 'Author' -%>:</b>
  <%= link_to @book.author.full_name, @book.author %>
</p>

<p>
  <b><%=t 'Description' -%>:</b>
  <%= @book.description %>
</p>

<p>
  <b><%=t 'First publish year' -%>:</b>
  <%= @book.publish_year %>
</p>

<p>
  <b><%=t 'Rental length' -%>:</b>
  <%= @book.rental_length %>
</p>

<p>
  <b><%=t :categories -%>:</b>
  <% @book.categories.each do |category| %>
    <span><%= link_to category.name, category -%>, </span>
  <% end %>
</p>


<%= link_to t(:manage_copies), book_copies_path(@book) %> |
<%= link_to t(:manage_categories), categories_of_book_path(@book) %> |
<%= link_to t('Edit'), edit_book_path(@book) %> |
<%= link_to t('Destroy'), @book, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to t('Back'), books_path %>