config/routes.rb
Wdbd::Application.routes.draw do

  resources :users

  resources :categories

  resources :books do
    resources :copies do
      member do
        post 'new_rent'
        post 'renew_rent'
        post 'finish_rent'
        post 'new_reservation'
        post 'execute_reservation'
        post 'cancel_reservation'
      end
    end
    member do
      get 'categories', :as => 'categories_of'
      post 'add_category', :as => 'add_category_of'
    end
  end
  match '/book/:id/remove_category/:category_id' => 'books#remove_category', :via => :delete, :as => 'remove_category_of_book'

  resources :authors

  root :to => 'books#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  <meta charset="utf-8"/>
  <meta name="description" content="">
  <meta name="author" content="">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <title>Zarządzanie biblioteką</title>
</head>
<body id="top">
<!--header -->
<div id="header-wrap"><header>
  <hgroup>
    <h1><a href="/">Zarządzanie biblioteką</a></h1>
  </hgroup>
<!--/header-->
</header></div>
<!-- content-wrap -->
<div id="content-wrap">
  <!-- content -->
  <div id="content" class="clearfix">
      <!-- main -->
    <div id="main">
      <div class="main-content">
      <!--<h2><a href="index.html">Archives for 2010</a></h2>-->
      <%= yield %>
      </div>
      <!-- /main -->
    </div>
    <!-- sidebar -->
    <div id="sidebar">
      <div class="sidemenu">
	<h3>Menu</h3>
	  <ul>
	    <li><%= link_to t(:books), books_path -%></li>
	    <li><%= link_to t(:authors), authors_path -%></li>
	    <li><%= link_to t(:categories), categories_path -%></li>
	    <li><%= link_to t(:users), users_path -%></li>
	  </ul>
	</div>
    <!-- /sidebar -->
    </div>
  <!-- content -->
  </div>
<!-- /content-out -->
</div>
<footer>
  <p class="footer-left">
    Zarządzanie biblioteką &copy; 2013 Mateusz Bednarski &amp; Mateusz Dudek &amp; Jacek Rybak
  </p>
  <p class="footer-right">
    <a href="http://mydevil.net" target="_blank"><img src="http://static.mydevil.net/banery/button-2.gif" /></a>
  </p>
</footer>
</body>
</html>